name: Automation Tests - Staging
on:
  push:
    branches: staging
  
jobs:
  test:
    environment: STAGING_ENV
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      ENV: ${{ secrets.STAGING_ENV }}
      
      RP_ENDPOINT: ${{ secrets.RP_ENDPOINT }}
      RP_PROJECT: ${{ secrets.RP_PROJECT }}
      RP_API_KEY: ${{ secrets.RP_API_KEY }}

      GITHUB_RUN_NUMBER: ${{ github.run_number }}
      GITHUB_REF_NAME: ${{ github.ref_name }}
      GITHUB_EVENT_NAME: ${{ github.event_name }}
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Cache Playwright Browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Create .env from secret
      run: |
        # write secret contents to .env without printing it to logs
        printf '%s' "$ENV" > .env
    - name: Run Playwright tests 
      run: npm run test
      continue-on-error: true
    - name: Install Allure CLI globally
      run: npm install -g allure-commandline
    - name: Generate Allure report
      run: npm run allure
    - name: Upload Allure report artifact
      if: always()
      uses: actions/upload-artifact@v5
      with:
        name: ${{ github.workflow }}_Build#${{ github.run_number }}
        path: reports/allure-report/
        retention-days: 30
